### ISSUE TITLE
test

### ISSUE THREAD

**Issue by idreamshen** [idreamshen/esphome-online-compiler#1]
```yaml
esphome:
  name: water-esp01
  friendly_name: water-esp01

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

wifi:
  ssid: "abcd1234"
  password: "abcd1234"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Esp01 Fallback Hotspot"
    password: "EK9mQos8OcTB"

captive_portal:
```
